name: Asad Shah
description: 
meta_description: ""

markdown: redcarpet
highlighter: pygments

baseurl: /
domain_name: 'http://asadmshah.xyz'
google_analytics: 'UA-44789032-1'

url:    "asadmshah.xyz"
author: "Asad Shah"

permalink: /:year/:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: drafts
    values:
      layout: post
